### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by xobs**
This is a first cut of Windows support for t-rec. It still requires imagemagick, but it appears to work.

It uses the `wgc-rust-demo` program to capture frames using Windows.Graphics.Capture. This enables capture of a variety of window types, and places a yellow border around the target window.

Current issues with this:

* It will default to capturing the window in front, rather than the window that was launched. This can be surprising if you alt-tab.
* It still tries to run `/bin/sh` by default. It's unclear what the default shell should be (cmd? powershell? pwsh?)
* It doesn't know anything about menubars, though with `Windows.Graphics.Capture` this appears to not be an issue since window decorations aren't captured to begin with.

t-rec_5

### CODE REVIEW

**Comment by sassman** [comment]
Nice! That looks awesome.

Regarding the things you've mentioned:
> It still tries to run /bin/sh by default. It's unclear what the default shell should be (cmd? powershell? pwsh?)
There is now PR #35 that would allow to change the default shell per platform. 

The other things I need to check once I got my windows setup running.

Thanks a lot for this first big shot!

**Comment by sassman** [comment]
t-rec_2

Nice, this is a very good starting point! Thanks again. 
Not sure if you prefer a review + feedback or in case you not have the time to polish this, I'd suggest merging it into a dedicated feature branch and I would iterate on it as well further. Please let me know what is your perference.

**Comment by xobs** [comment]
I think I'd prefer the feature branch for now, if that's okay with you.

As I said, the code was pretty much directly ported over from the winrt demo, and uses an old, prerelease version of the library. It will need to be changed to even work with any published version of `winrt`.

**Comment by sassman** [comment]
That is totally fine with me. I thank you very much for this first working draft, that helps a lot.
I'll keep the feature branch in sync with `main` and going to push frequent so that In you want to support there you can at any time fork and continue.

**Pull request merged**
