### PR TITLE
Allow building on NetBSD

### PR DESCRIPTION
**Pull request by 0323pin**
I've successfully build, installed and tested `t-rec` on NetBSD.
Please consider the following patches to allow support for NetBSD. I will merge the package into our repositories during the day.

t-rec_on_NetBSD

### CODE REVIEW

**Comment by sassman** [comment]
@0323pin how cool is that, it runs on NetBSD! Nice thanks for your PR, very much appreciated.

**Comment by sassman** [comment]
only clippy was not happy with the formatting:

```diff
-#[cfg(all(
-    not(target_os = "linux"),
-    not(target_os = "netbsd"),
-))]
+#[cfg(all(not(target_os = "linux"), not(target_os = "netbsd"),))]
```

**Review by sassman — APPROVED** [review]

**Comment by 0323pin** [comment]
> only clippy was not happy with the formatting:
> 
> ```diff
> -#[cfg(all(
> -    not(target_os = "linux"),
> -    not(target_os = "netbsd"),
> -))]
> +#[cfg(all(not(target_os = "linux"), not(target_os = "netbsd"),))]
> ```

This is weird, I did exactly the opposite on another PR for another project.
But, that's fine with me :)

Btw, package merged, http://mail-index.netbsd.org/pkgsrc-changes/2022/10/06/msg261582.html

**Comment by 0323pin** [comment]
@sassman One last thing, I think you could safely add FreeBSD, OpenBSD and DragonFlyBSD the same way but, I don't use these and have no possibility to test.

**Comment by 0323pin** [comment]
@sassman All good?

I think there's a comma too much at end,
`#[cfg(all(not(target_os = "linux"), not(target_os = "netbsd"),))]`
shoud be `#[cfg(all(not(target_os = "linux"), not(target_os = "netbsd")))]`

**Comment by 0323pin** [comment]
@sassman This is interesting. See the suggestion here:

2022-10-07-060239_1366x768_scrot

**Review by sassman — APPROVED** [review]

**Comment by sassman** [comment]
> @sassman This is interesting. See the suggestion here:
> 
> 2022-10-07-060239_1366x768_scrot

The latest changes fixed the formatting checks, thanks for going the extra mile.

**Comment by 0323pin** [comment]
@sassman thanks!

**Pull request merged**
